name: build
on:
  push:
    branches: [ "main" ]

jobs:
  day_01:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./days/01
    steps:
      - uses: actions/checkout@v4
      - name: setup dotnet
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 8.0.x
      - name: run
        run: dotnet run
  day_02:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./days/02
    steps:
      - uses: actions/checkout@v4
      - name: setup dotnet
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 8.0.x
      - name: run
        run: dotnet run

  day_03:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./days/03
    steps:
      - uses: actions/checkout@v4
      - name: setup go
        uses: actions/setup-go@v4
        with:
            go-version: '1.21'
      - name: run
        run: go run main.go

